import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Roboto } from 'next/font/google'
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
// const roboto = Roboto({
//   weight: '400',
//   variable: "--font-get-roboto",
//   subsets: ['latin'],
//   display: 'swap',
// })
export const metadata: Metadata = {
  title: "Báo cáo hằng ngày",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
